{
 "title": "CDA Source Connector",
 "description": "Monitor CDA Source Connector",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "kafka_connect_cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(kafka_connect_cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_connect_app_info{job=\"kafka-connect\", env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"},instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{job=\"kafka-connect\", env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Records Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mycompany_cda_connector_records_number{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",record_type=~\".*\"}",
     "legendFormat": "{{record_type}}"
    }
   ]
  },
  {
   "title": "Parquet Files Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mycompany_cda_connector_file_convert_count{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",record_type=~\".*\"}",
     "legendFormat": "{{record_type}}"
    }
   ]
  },
  {
   "title": "Parquet File Convert Rate (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mycompany_cda_connector_file_convert_mean{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",record_type=~\".*\"}",
     "legendFormat": "{{record_type}}"
    }
   ]
  },
  {
   "title": "Parquet Schema Convert Rate (ms)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mycompany_cda_connector_file_convert_mean{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",record_type=~\".*\"}",
     "legendFormat": "{{record_type}}"
    }
   ]
  },
  {
   "title": "Records Per Parquet File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(mycompany_cda_connector_records_number{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",record_type=~\".*\"}/mycompany_cda_connector_file_convert_count{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",record_type=~\".*\"})",
     "legendFormat": "{{record_type}}"
    }
   ]
  },
  {
   "title": "Record Convert Rate (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "mycompany_cda_connector_file_convert_mean{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",record_type=~\".*\"}/(mycompany_cda_connector_records_number{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",record_type=~\".*\"}/mycompany_cda_connector_file_convert_count{job=\"kafka-connect\", env=\"$env\",instance=~\"$instance\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\",record_type=~\".*\"})",
     "legendFormat": "{{record_type}}"
    }
   ]
  }
 ]
}